name: model-wine-quality
on: [push]
permissions:
  id-token: write
  contents: write            
  security-events: write  

jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: iterative/setup-cml@v1
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Train Model
        run: python train.py
      - name: Prepare CML Report
        run: |
          echo "MODEL METRICS" > report.md
          cat metrics.txt >> report.md
          echo "Data Visualization:" >> report.md
          echo '![](./feature_importance.png)' >> report.md
          echo '![](./residuals.png)' >> report.md
      - name: Publish CML Report
        
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cml comment create --publish report.md
